---
title: "Training a DNN with Noisy Labels"
author: "Jan Sauer"
output: 
   BiocStyle::html_document:
    code_folding: hide
    df_print: paged
    toc_depth: 4
    toc_float: true
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup}
library(ggplot2)

custom_theme <- function(base_size=14, base_family="Helvetica") {
  library(grid)
  library(ggthemes)
  (theme_foundation(base_size=base_size, base_family=base_family)
    + theme(plot.title = element_text(face = "bold",
                                      size = rel(1.2), hjust = 0.5), 
            plot.subtitle = element_text(hjust = 0.5),
            plot.caption = element_text(hjust = 0),
            text = element_text(),
            panel.background = element_rect(colour = NA),
            plot.background = element_rect(colour = NA),
            panel.border = element_rect(colour = NA),
            axis.title = element_text(face = "bold",size = rel(1)),
            axis.title.y = element_text(angle=90,vjust =2),
            axis.title.x = element_text(vjust = -0.2),
            axis.text = element_text(), 
            axis.line = element_line(colour="black"),
            axis.ticks = element_line(),
            # panel.grid.major = element_line(colour="#f0f0f0"),
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            legend.key = element_rect(colour = NA),
            legend.position = "right",
            legend.direction = "vertical",
            legend.key.size= unit(0.5, "cm"),
            legend.spacing = unit(1, "cm"),
            legend.title = element_text(face="italic"),
            plot.margin=unit(c(10,5,5,5),"mm"),
            strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
            strip.text = element_text(face="bold")))}
custom_fill <- function(...){
  library(scales)
  discrete_scale("fill","Publication",manual_pal(values = c(
    "#386cb0","#fdb462","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99",
    "#984ea3","#ffff33")), ...)}
custom_color <- function(...){
  library(scales)
  discrete_scale("colour","Publication",manual_pal(values = c(
    "#386cb0","#fdb462","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99",
    "#984ea3","#ffff33")), ...)}
```


# Introduction

I trained a "deep" convolutional network (it's structure was conv-conv-pool-conv-conv-pool-dense) on noisy data. To this end, I used the MNIST dataset and randomly changed a fraction of the labels. The scrambled labels were guaranteed to be wrong.

```{r}
scrambling_results = read.csv(
  file = "ResultsScrambling_mnist_conv.csv", header = TRUE, row.names = NULL)

ggplot(data = scrambling_results, mapping = aes(x = X, y = TrueF1)) + 
  geom_point(size = 4) + geom_line(size = 2) + custom_theme() + 
  coord_fixed() + labs(
    x = "Scrambling Factor", y = "F1-Score", 
    caption = paste0(
       "F1-Score of DNN trained on scrambled\n",
       "labels versus the true labels"))
ggsave("ResultsScrambling_mnist_conv.pdf", width = 5, height = 5)
```
